### ISSUE TITLE
SIM not detecting

### ISSUE THREAD

**Issue by ChillarAnand** [ashwinr64/android_device_motorola_athene#14]
I have installed CM 13 on g4 plus(XT1643(Indian variant)) and found that it is not detecting sim cards.

**Comment by ghost** [comment]
@ChillarAnand I have the same variant but works perfectly fine for me. This maybe an issue with you having a older firmware. Did you get any OTA after you got the device?

**Comment by ChillarAnand** [comment]
No, I didn't get OTA. I got device couple of days back.

**Comment by ghost** [comment]
You might need to check the build number then. Make sure your on latest. A couple of people with XT1643 have reported it to be working. I dont know about people in XDA.

**Comment by ChillarAnand** [comment]
Thank you.
